# Generated by Django 5.0.2 on 2024-03-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_filesdata_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=10)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='filesData',
        ),
    ]
