# Generated by Django 5.0.2 on 2024-03-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fileData',
            new_name='filesData',
        ),
    ]
